"""Frozen BRW-014 label definitions (canonical scientific contract)."""

from __future__ import annotations

LABEL_DEFINITIONS: list[dict] = [
    {
        "name": "soc_reference_percent_charge",
        "type": "reference_label",
        "description": "V2 charge-direction reference SOC (0=empty at segment start, 100=full at CC-CV end)",
        "formula": "100 * Q_charged_since_empty(t) / Q_charge_segment_total",
        "unit": "percent",
        "method": "PROTOCOL_ANCHORED_SEGMENT_NORMALIZED",
        "anchor": "CHARGE_SEGMENT_START (empty; cycle-1 start = ASSUMED_INITIAL_ANCHOR)",
        "denominator": "measured charge segment total (CC+CV)",
        "temporality": "RETROSPECTIVE_SEGMENT_NORMALIZED_REFERENCE",
        "eligible_for_supervised_learning": True,
        "leakage_notes": "segment total known only after segment completion; never GLOBAL_DATASET_FIT",
        "version": "0.2.0",
    },
    {
        "name": "soc_reference_percent_discharge",
        "type": "reference_label",
        "description": "V2 discharge-direction reference SOC (100=full at segment start, 0=empty at end)",
        "formula": "100 * (1 - Q_discharged_since_full(t) / Q_discharge_segment_total)",
        "unit": "percent",
        "method": "PROTOCOL_ANCHORED_SEGMENT_NORMALIZED",
        "anchor": "DISCHARGE_SEGMENT_START (full, established by completed CC-CV charge)",
        "denominator": "measured discharge segment total",
        "temporality": "RETROSPECTIVE_SEGMENT_NORMALIZED_REFERENCE",
        "eligible_for_supervised_learning": True,
        "leakage_notes": "segment total known only after segment completion",
        "version": "0.2.0",
    },
    {
        "name": "soc_reference_percent_rest",
        "type": "reference_label",
        "description": "Rest SOC propagated from the previous protocol-contiguous segment end (same cycle only)",
        "formula": "SOC = previous valid segment-end SOC",
        "unit": "percent",
        "method": "REST_PROPAGATED_FROM_PREVIOUS_VALID_REFERENCE",
        "anchor": "PROPAGATED_REST_ANCHOR",
        "denominator": "not applicable (no re-integration)",
        "temporality": "RETROSPECTIVE_SEGMENT_NORMALIZED_REFERENCE",
        "eligible_for_supervised_learning": True,
        "leakage_notes": "propagation never crosses cycle boundaries",
        "version": "0.2.0",
    },
    {
        "name": "soc_integral_unbounded_percent",
        "type": "diagnostic_only",
        "description": "V1-style integral with charge normalized by discharge capacity (CE=1 assumption); kept for apparent-CE audit only",
        "formula": "100 * Q_charged_since_empty(t) / Q_discharge_capacity_total",
        "unit": "percent",
        "method": "DIAGNOSTIC_INTEGRAL",
        "anchor": "not applicable",
        "reference_capacity_policy": "not applicable",
        "temporality": "RETROSPECTIVE_FULL_CYCLE_REFERENCE",
        "eligible_for_supervised_learning": False,
        "leakage_notes": "NOT a target/predictor/canonical label; exposes apparent coulombic-efficiency artifact (>100 at CV end)",
        "version": "0.2.0",
    },
    {
        "name": "soh_capacity_reference_percent",
        "type": "reference_label",
        "description": "Capacity-based reference SOH (baseline-relative)",
        "formula": "100 * Q_discharge_measured(cycle) / Q_ref",
        "unit": "percent",
        "method": "CAPACITY_BASELINE_RATIO",
        "anchor": "BASELINE_CYCLE_COMPLETE_DISCHARGE",
        "reference_capacity_policy": "WITHIN_EXPERIMENT_BASELINE",
        "temporality": "RETROSPECTIVE_BASELINE_REFERENCE",
        "eligible_for_supervised_learning": True,
        "leakage_notes": "Baseline SOH=100 is definitional; only 2 independent cycle states in current baseline",
        "version": "0.1.0",
    },
    {
        "name": "vendor_soc_dod_percent",
        "type": "diagnostic_only",
        "description": "Vendor SOC/DOD(%) raw field; NOT promoted to a reference label",
        "formula": "vendor proprietary (unproven semantics)",
        "unit": "percent",
        "method": "VENDOR_FIELD",
        "anchor": "UNKNOWN",
        "reference_capacity_policy": "NOT_APPLICABLE",
        "temporality": "UNKNOWN",
        "eligible_for_supervised_learning": False,
        "leakage_notes": "Vendor mixed field: 0->100 in BOTH charge and discharge; comparison diagnostic only",
        "version": "0.2.0",
    },
    {
        "name": "absolute_tof",
        "type": "reserved_not_emitted",
        "description": "Absolute time-of-flight; BLOCKED until sampling/calibration metadata exists",
        "formula": "RESERVED: (arrival_sample_index - trigger_sample_index) / sampling_rate_hz",
        "unit": "s",
        "method": "NOT_SELECTED",
        "anchor": "TRIGGER_ZERO (missing)",
        "reference_capacity_policy": "NOT_APPLICABLE",
        "temporality": "NOT_APPLICABLE",
        "eligible_for_supervised_learning": False,
        "leakage_notes": "Frame acquisition interval (~10s) is never the waveform sampling period",
        "version": "0.1.0-reserved",
    },
]
