"""Frozen BRW-014 label definitions (canonical scientific contract)."""

from __future__ import annotations

LABEL_DEFINITIONS: list[dict] = [
    {
        "name": "soc_reference_percent",
        "type": "reference_label",
        "description": "Derived reference SOC label from electrical protocol/capacity measurements",
        "formula": "DISCHARGE: 100*(1 - Q_discharged_since_full/Q_ref); CHARGE: 100*Q_charged_since_empty/Q_ref",
        "unit": "percent",
        "method": "COULOMB_COUNTING_PROTOCOL_ANCHORED",
        "anchor": "FULL_CHARGE_CV_END / EMPTY_DISCHARGE_END",
        "reference_capacity_policy": "WITHIN_EXPERIMENT_BASELINE_OR_SAME_CYCLE",
        "temporality": "RETROSPECTIVE_FULL_CYCLE_REFERENCE",
        "eligible_for_supervised_learning": True,
        "leakage_notes": "Q_ref uses same-cycle endpoint information (retrospective); never GLOBAL_DATASET_FIT",
        "version": "0.1.0",
    },
    {
        "name": "soh_capacity_reference_percent",
        "type": "reference_label",
        "description": "Capacity-based reference SOH (baseline-relative)",
        "formula": "100 * Q_discharge_measured(cycle) / Q_ref",
        "unit": "percent",
        "method": "CAPACITY_BASELINE_RATIO",
        "anchor": "BASELINE_CYCLE_COMPLETE_DISCHARGE",
        "reference_capacity_policy": "WITHIN_EXPERIMENT_BASELINE",
        "temporality": "RETROSPECTIVE_BASELINE_REFERENCE",
        "eligible_for_supervised_learning": True,
        "leakage_notes": "Baseline SOH=100 is definitional; only 2 independent cycle states in current baseline",
        "version": "0.1.0",
    },
    {
        "name": "vendor_soc_dod_percent",
        "type": "diagnostic_only",
        "description": "Vendor SOC/DOD(%) raw field; NOT promoted to a reference label",
        "formula": "vendor proprietary (unproven semantics)",
        "unit": "percent",
        "method": "VENDOR_FIELD",
        "anchor": "UNKNOWN",
        "reference_capacity_policy": "NOT_APPLICABLE",
        "temporality": "UNKNOWN",
        "eligible_for_supervised_learning": False,
        "leakage_notes": "Vendor mixed field: 0->100 in BOTH charge and discharge; comparison diagnostic only",
        "version": "0.1.0",
    },
    {
        "name": "absolute_tof",
        "type": "reserved_not_emitted",
        "description": "Absolute time-of-flight; BLOCKED until sampling/calibration metadata exists",
        "formula": "RESERVED: (arrival_sample_index - trigger_sample_index) / sampling_rate_hz",
        "unit": "s",
        "method": "NOT_SELECTED",
        "anchor": "TRIGGER_ZERO (missing)",
        "reference_capacity_policy": "NOT_APPLICABLE",
        "temporality": "NOT_APPLICABLE",
        "eligible_for_supervised_learning": False,
        "leakage_notes": "Frame acquisition interval (~10s) is never the waveform sampling period",
        "version": "0.1.0-reserved",
    },
]
