from __future__ import annotations

RECORD_COLUMN_MAPPING = {
    "数据序号": "record_index_raw",
    "循环号": "cycle_index_raw",
    "工步号": "step_index_raw",
    "工步开始结束标识": "step_boundary_raw",
    "工步类型": "step_type_raw",
    "时间": "step_time_s",
    "总时间": "elapsed_time_s",
    "电流(A)": "current_a",
    "电压(V)": "voltage_v",
    "容量(Ah)": "capacity_ah",
    "比容量(mAh/g)": "specific_capacity_mah_per_g",
    "充电容量(Ah)": "charge_capacity_ah",
    "充电比容量(mAh/g)": "charge_specific_capacity_mah_per_g",
    "放电容量(Ah)": "discharge_capacity_ah",
    "放电比容量(mAh/g)": "discharge_specific_capacity_mah_per_g",
    "能量(Wh)": "energy_wh",
    "比能量(mWh/g)": "specific_energy_mwh_per_g",
    "充电能量(Wh)": "charge_energy_wh",
    "充电比能量(mWh/g)": "charge_specific_energy_mwh_per_g",
    "放电能量(Wh)": "discharge_energy_wh",
    "放电比能量(mWh/g)": "discharge_specific_energy_mwh_per_g",
    "绝对时间": "timestamp",
    "功率(W)": "power_w",
    "dQ/dV(mAh/V)": "dqdv_mah_per_v",
    "dQm/dV(mAh/V.g)": "dqm_dv_mah_per_v_g",
    "接触电阻(mΩ)": "contact_resistance_mohm",
    "模块启停开关": "module_switch_raw",
    "SOC/DOD(%)": "soc_dod_percent",
    "LgD": "lgd_raw",
}

CYCLE_COLUMN_MAPPING = {
    "循环号": "cycle_index_raw",
    "起始绝对时间": "start_timestamp",
    "结束绝对时间": "end_timestamp",
    "充电容量(Ah)": "charge_capacity_ah",
    "放电容量(Ah)": "discharge_capacity_ah",
    "充电比容量(mAh/g)": "charge_specific_capacity_mah_per_g",
    "放电比容量(mAh/g)": "discharge_specific_capacity_mah_per_g",
    "充放电效率(%)": "coulombic_efficiency_percent",
    "充电能量(Wh)": "charge_energy_wh",
    "放电能量(Wh)": "discharge_energy_wh",
    "充电比能量(mWh/g)": "charge_specific_energy_mwh_per_g",
    "放电比能量(mWh/g)": "discharge_specific_energy_mwh_per_g",
    "恒流充入比率(%)": "constant_current_charge_ratio_percent",
    "恒流充入容量(Ah)": "constant_current_charge_capacity_ah",
    "平台容量(Ah)": "plateau_capacity_ah",
    "平台比容量": "plateau_specific_capacity_raw",
    "平台容量效率(%)": "plateau_capacity_efficiency_percent",
    "平台时间": "plateau_time_raw",
    "充电电容(F)": "charge_capacitance_f",
    "放电电容(F)": "discharge_capacitance_f",
    "中值电压(V)": "median_voltage_v",
    "容量保持率(%)": "capacity_retention_percent",
    "充电时间": "charge_time_raw",
    "放电时间": "discharge_time_raw",
    "净放电容量(Ah)": "net_discharge_capacity_ah",
    "净放电能量(Wh)": "net_discharge_energy_wh",
    "能量效率(%)": "energy_efficiency_percent",
    "T1 辅助通道起始温度(℃)": "t1_start_temperature_c",
    "T1 辅助通道结束温度(℃)": "t1_end_temperature_c",
    "T1 辅助通道最高温度(℃)": "t1_max_temperature_c",
    "T1 辅助通道最低温度(℃)": "t1_min_temperature_c",
    "V1 辅助通道起始电压(V)": "v1_start_voltage_v",
    "V1 辅助通道结束电压(V)": "v1_end_voltage_v",
    "V1 辅助通道最高电压(V)": "v1_max_voltage_v",
    "V1 辅助通道最低电压(V)": "v1_min_voltage_v",
    "T1 充电最高温度(℃)": "t1_charge_max_temperature_c",
    "T1 充电最低温度(℃)": "t1_charge_min_temperature_c",
    "T1 放电最高温度(℃)": "t1_discharge_max_temperature_c",
    "T1 放电最低温度(℃)": "t1_discharge_min_temperature_c",
}

STEP_COLUMN_MAPPING = {
    "循环号": "cycle_index_raw",
    "工步号": "step_index_raw",
    "工步序号": "step_sequence_raw",
    "工步类型": "step_type_raw",
    "工步时间": "step_time_s",
    "起始绝对时间": "start_timestamp",
    "结束绝对时间": "end_timestamp",
    "容量(Ah)": "capacity_ah",
    "比容量(mAh/g)": "specific_capacity_mah_per_g",
    "充电容量(Ah)": "charge_capacity_ah",
    "充电比容量(mAh/g)": "charge_specific_capacity_mah_per_g",
    "放电容量(Ah)": "discharge_capacity_ah",
    "放电比容量(mAh/g)": "discharge_specific_capacity_mah_per_g",
    "净放电容量(Ah)": "net_discharge_capacity_ah",
    "能量(Wh)": "energy_wh",
    "比能量(mWh/g)": "specific_energy_mwh_per_g",
    "充电能量(Wh)": "charge_energy_wh",
    "充电比能量(mWh/g)": "charge_specific_energy_mwh_per_g",
    "放电能量(Wh)": "discharge_energy_wh",
    "放电比能量(mWh/g)": "discharge_specific_energy_mwh_per_g",
    "净放电能量(Wh)": "net_discharge_energy_wh",
    "超级电容(F)": "capacitance_f",
    "起始电压(V)": "start_voltage_v",
    "充电起始电压(V)": "charge_start_voltage_v",
    "放电起始电压(V)": "discharge_start_voltage_v",
    "结束电压(V)": "end_voltage_v",
    "充电终止电压(V)": "charge_end_voltage_v",
    "放电终止电压(V)": "discharge_end_voltage_v",
    "充电中值电压(V)": "charge_median_voltage_v",
    "放电中值电压(V)": "discharge_median_voltage_v",
    "起始电流(A)": "start_current_a",
    "结束电流(A)": "end_current_a",
    "DCIR(mΩ)": "dcir_mohm",
    "T1 辅助通道起始温度(℃)": "t1_start_temperature_c",
    "T1 辅助通道结束温度(℃)": "t1_end_temperature_c",
    "T1 辅助通道最高温度(℃)": "t1_max_temperature_c",
    "T1 辅助通道最低温度(℃)": "t1_min_temperature_c",
    "V1 辅助通道起始电压(V)": "v1_start_voltage_v",
    "V1 辅助通道结束电压(V)": "v1_end_voltage_v",
    "V1 辅助通道最高电压(V)": "v1_max_voltage_v",
    "V1 辅助通道最低电压(V)": "v1_min_voltage_v",
}

REQUIRED_COLUMNS = {
    "record": {
        "数据序号",
        "循环号",
        "工步号",
        "工步类型",
        "绝对时间",
        "电流(A)",
        "电压(V)",
        "容量(Ah)",
    },
    "cycle": {"循环号", "起始绝对时间", "结束绝对时间"},
    "step": {"循环号", "工步号", "工步类型", "起始绝对时间", "结束绝对时间"},
}
