"""Frozen V1 sample-domain feature definitions for BRW-013.

These are the canonical scientific contract. All features are sample-domain;
none requires a sampling rate, and no physical time/frequency feature is
defined here.
"""

from __future__ import annotations

FEATURE_DEFINITIONS: list[dict] = [
    {
        "name": "waveform_min_a_u",
        "version": "0.1.0",
        "description": "Minimum raw waveform value",
        "formula": "min(x)",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_max_a_u",
        "version": "0.1.0",
        "description": "Maximum raw waveform value",
        "formula": "max(x)",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_mean_a_u",
        "version": "0.1.0",
        "description": "Mean of the raw waveform (DC/offset)",
        "formula": "mean(float64(x))",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_std_a_u",
        "version": "0.1.0",
        "description": "Population standard deviation (ddof=0)",
        "formula": "std(float64(x), ddof=0)",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_rms_a_u",
        "version": "0.1.0",
        "description": "Root-mean-square amplitude",
        "formula": "sqrt(mean(float64(x)**2))",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_p2p_a_u",
        "version": "0.1.0",
        "description": "Peak-to-peak amplitude",
        "formula": "max(x) - min(x)",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_abs_peak_a_u",
        "version": "0.1.0",
        "description": "Maximum absolute waveform value",
        "formula": "max(abs(float64(x)))",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_abs_peak_sample_index",
        "version": "0.1.0",
        "description": "Sample index of the first absolute peak",
        "formula": "first argmax(abs(x))",
        "unit": "sample",
        "dtype": "int64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "waveform_energy_sum_sq_a_u2",
        "version": "0.1.0",
        "description": "Sum of squared samples (energy-like, sample-domain)",
        "formula": "sum(float64(x)**2)",
        "unit": "a.u.^2*sample",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "envelope_peak_a_u",
        "version": "0.1.0",
        "description": "Peak of the raw analytic Hilbert envelope",
        "formula": "max(abs(hilbert(float64(x))))",
        "unit": "a.u.",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "envelope_peak_sample_index",
        "version": "0.1.0",
        "description": "Sample index of the first envelope peak",
        "formula": "first argmax(abs(hilbert(float64(x))))",
        "unit": "sample",
        "dtype": "int64",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if waveform nonfinite",
    },
    {
        "name": "xcorr_reference_measurement_event_id",
        "version": "0.1.0",
        "description": "Reference event id for relative cross-correlation",
        "formula": "per-asset first valid event",
        "unit": "id",
        "dtype": "str",
        "requires_sampling_rate": False,
        "preprocessing": "none",
        "null_behavior": "null if no reference",
    },
    {
        "name": "xcorr_shift_samples",
        "version": "0.1.0",
        "description": "Relative lag vs the per-asset reference (positive = later/larger index)",
        "formula": "lag of argmax(correlate(current, reference))",
        "unit": "samples",
        "dtype": "int64",
        "requires_sampling_rate": False,
        "preprocessing": "mean-center only",
        "null_behavior": "null if denominator zero or nonfinite",
    },
    {
        "name": "xcorr_peak_coefficient",
        "version": "0.1.0",
        "description": "Normalized dimensionless cross-correlation peak",
        "formula": "corr_max / sqrt(sum(x0**2)*sum(r0**2))",
        "unit": "dimensionless",
        "dtype": "float64",
        "requires_sampling_rate": False,
        "preprocessing": "mean-center only",
        "null_behavior": "null if denominator zero or nonfinite",
    },
]
