import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { client, ApiError } from "../../api/client";
import { Button } from "../../components/ui/button";
import { Badge } from "../../components/ui/badge";
import { PageHeader, LoadingState, ErrorState, EmptyState } from "../../components/workbench/shared";
import { ParameterDialog } from "../../components/workbench/ParameterDialog";
import { displayName } from "../../lib/presentation";
import { RunsPage } from "../RunsPage";
import { DataWorkspacePage } from "../DataWorkspacePage";
import { DatasetSplitPage } from "../DatasetSplitPage";
import { WorkspacePage } from "../WorkspacePage";

function Parameters() {
  const {batteryId="",experimentId=""}=useParams(); const [selected,setSelected]=useState("");
  const params=useQuery({queryKey:["parameters",batteryId,experimentId],queryFn:()=>client.listParameters(batteryId,experimentId),retry:false});
  if(params.isLoading)return <LoadingState/>;
  if(params.error && !(params.error instanceof ApiError && params.error.code==="NOT_FOUND"))return <ErrorState error={params.error} retry={()=>void params.refetch()}/>;
  const sets=params.data?.data??[]; const set=sets.find(s=>s.parameter_set_id===selected)??(sets.length===1?sets[0]:undefined);
  const definitions=[{key:"ultrasound.sampling_rate_hz",label:"Sampling rate",hint:"Required for absolute timing"},{key:"ultrasound.trigger_sample_index",label:"Trigger / time-zero",hint:"Instrument-defined reference"},{key:"ultrasound.system_delay_s",label:"System delay",hint:"Calibration reference"},{key:"electrical.reference_capacity_ah",label:"Reference capacity",hint:"Reference SOC interpretation"},{key:"experiment.ultrasound_path_length_m",label:"Acoustic path",hint:"Never assumed from cell thickness"}];
  return <section className="panel"><div className="flex justify-between gap-4 items-center mb-6"><div><h2>Scientific parameters</h2><p className="muted text-sm mt-1">Record what you know. Keep unknown values explicit.</p></div><ParameterDialog/></div>
    {sets.length>1 && <label className="field mb-5">Parameter version<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a version to inspect</option>{sets.map((s,i)=><option key={s.parameter_set_id} value={s.parameter_set_id}>Version {i+1}</option>)}</select><span className="text-xs muted">No version is assumed to be the active version.</span></label>}
    {definitions.map(d=>{const entry=set?.effective[d.key]; const record=entry && typeof entry==="object"?entry as Record<string,unknown>:null;return <div className="data-row" key={d.key}><div className="flex-1"><h3>{d.label}</h3><p className="muted text-sm">{d.hint}</p></div><div className="text-right"><p className="font-medium">{record?.value!==undefined && record.value!==null ? `${String(record.value)} ${String(record.unit??"")}` : "—"}</p><span className="text-xs muted">{record?.verification_status ? displayName(String(record.verification_status)) : "Not resolved"}</span></div></div>;})}
    <div className="notice mt-6">Adding a sampling rate records a user-provided value. Verified timing and downstream results remain controlled by the scientific service.</div>
    <details className="mt-5"><summary>Parameter provenance & exact values</summary>{sets.length===0?<p className="muted">No parameter versions available.</p>:sets.map(s=><div key={s.parameter_set_id} className="py-3"><p className="text-xs break-all">{s.parameter_set_id}</p><pre className="text-xs whitespace-pre-wrap break-all mt-2">{JSON.stringify(s.effective,null,2)}</pre></div>)}</details>
    <Button variant="link" asChild className="px-0 mt-3"><Link to={`/experiments/${batteryId}/${experimentId}/advanced/runs`}>Resolve other pending parameter requests<ArrowRight/></Link></Button>
  </section>;
}
function Evidence(){const {batteryId="",experimentId=""}=useParams();const q=useQuery({queryKey:["evidence",batteryId,experimentId],queryFn:()=>client.getEvidence(batteryId,experimentId)});if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error} retry={()=>void q.refetch()}/>;return <section className="panel overflow-auto"><h2 className="mb-5">Evidence register</h2><table><thead><tr><th>Evidence type</th><th>Source</th><th>Availability</th></tr></thead><tbody>{q.data?.data.evidence.map((e,i)=><tr key={i}><td><Badge variant="secondary">{displayName(e.evidence_type)}</Badge></td><td><details><summary>Source {i+1}</summary><code className="text-xs">{e.evidence_ref}</code><p className="text-xs break-all">{e.artifact_id}</p></details></td><td>{displayName(e.artifact_availability)}</td></tr>)}</tbody></table></section>;}
function Lineage(){const {batteryId="",experimentId=""}=useParams();const q=useQuery({queryKey:["lineage",batteryId,experimentId],queryFn:()=>client.getLineage(batteryId,experimentId)});if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error} retry={()=>void q.refetch()}/>;return <section className="panel"><h2>Research lineage</h2><p className="muted mt-2 mb-6">Stages returned by the scientific service. Expand a stage for its exact identity.</p><ol className="space-y-3">{q.data?.data.lineage_chain.map((n,i)=><li key={`${n.artifact_type}-${i}`} className="border-l-2 border-primary pl-5"><details><summary>{displayName(n.artifact_type)} <Badge variant="outline" className="ml-3">{displayName(n.status)}</Badge></summary><code className="text-xs">{n.artifact_id??"No artifact available"}</code></details></li>)}</ol></section>;}
export function AdvancedPage(){const {batteryId="",experimentId="",section="parameters"}=useParams();const tabs=["parameters","evidence","lineage","artifacts","runs","data","dataset-split"];return <><PageHeader eyebrow="Details when you need them" title="Advanced" description="Parameters, provenance, and reproducibility tools."/><nav aria-label="Advanced navigation" className="flex gap-2 flex-wrap mb-7">{tabs.map(t=><Button key={t} variant={section===t?"secondary":"ghost"} asChild><Link to={`/experiments/${batteryId}/${experimentId}/advanced/${t}`}>{t==="dataset-split"?"Datasets & splits":t[0]!.toUpperCase()+t.slice(1)}</Link></Button>)}</nav>{section==="parameters"?<Parameters/>:section==="evidence"?<Evidence/>:section==="lineage"?<Lineage/>:section==="runs"?<div className="legacy-view"><RunsPage/></div>:section==="data"?<div className="legacy-view"><DataWorkspacePage/></div>:section==="dataset-split"?<div className="legacy-view"><DatasetSplitPage/></div>:section==="artifacts"||section==="workspace"?<div className="legacy-view"><WorkspacePage/></div>:<EmptyState title="View unavailable">Choose an Advanced section above.</EmptyState>}</>;}
