import { lazy, Suspense, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { ChevronLeft, ChevronRight, Hand, MousePointer2, Plus, RotateCcw, ZoomIn } from "lucide-react";
import { client } from "../../api/client";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Badge } from "../../components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "../../components/ui/dialog";
import { PageHeader, LoadingState, ErrorState, EmptyState, BlockedValue, ScopeNote } from "../../components/workbench/shared";
import { ParameterDialog } from "../../components/workbench/ParameterDialog";
import { numberText } from "../../lib/presentation";
const WaveformPlot = lazy(()=>import("../../components/workbench/WaveformPlot"));

export function WaveformWorkbench() {
  const {batteryId="",experimentId=""}=useParams(); const qc=useQueryClient();
  const [position,setPosition]=useState(0); const [mode,setMode]=useState<"zoom"|"pan"|"select">("zoom"); const [reset,setReset]=useState(0);
  const [draft,setDraft]=useState<{start:number;end:number}|null>(null); const [confirm,setConfirm]=useState(false); const [name,setName]=useState(""); const [message,setMessage]=useState("");
  const frames=useQuery({queryKey:["waveform-frames",batteryId,experimentId],queryFn:()=>client.listWaveformFrames(batteryId,experimentId)});
  const frame=frames.data?.data.frames[position];
  const preview=useQuery({queryKey:["waveform-frame",batteryId,experimentId,frame?.frame_index],queryFn:()=>client.getWaveformFrame(batteryId,experimentId,frame!.frame_index,1000),enabled:!!frame});
  const gates=useQuery({queryKey:["gates",batteryId,experimentId],queryFn:()=>client.listGates(batteryId,experimentId)});
  const events=useQuery({queryKey:["events-preview",batteryId,experimentId],queryFn:()=>client.getMeasurementEvents(batteryId,experimentId,50)});
  const status=useQuery({queryKey:["status",batteryId,experimentId],queryFn:()=>client.getStatus(batteryId,experimentId)});
  const commit=useMutation({mutationFn:()=>client.createGate({battery_id:batteryId,experiment_id:experimentId,gate_name:name.trim() || "Selected region",start_sample:draft!.start,end_sample:draft!.end,waveform_length:preview.data!.data.waveform_length}), onSuccess:r=>{setConfirm(false);setDraft(null);setName("");setMessage(r.data.reuse_status==="REUSED"?"Existing gate reused.":"Gate saved to this experiment.");void qc.invalidateQueries({queryKey:["gates",batteryId,experimentId]});}});
  function select(start:number,end:number){const max=(preview.data?.data.waveform_length??1)-1; const s=Math.max(0,Math.min(start,max));const e=Math.max(s,Math.min(end,max));if(e>s){setDraft({start:s,end:e});setMessage("");}}
  function changePosition(next:number){setPosition(next);setDraft(null);setMessage("");}
  if(frames.isLoading) return <LoadingState/>;
  if(frames.error) return <ErrorState error={frames.error} retry={()=>void frames.refetch()}/>;
  if(!frames.data?.data.frames.length) return <EmptyState title="No waveforms yet" to={`/experiments/${batteryId}/${experimentId}/advanced/data`} action="Review experiment data">Import and process ultrasound data to explore waveforms.</EmptyState>;
  const matches=events.data?.data.events.filter(e=>e.frame_index_raw===frame?.frame_index)??[];
  const unique=(frames.data.data.frames.filter(f=>f.frame_index===frame?.frame_index).length===1 && matches.length===1) ? matches[0] : undefined;
  const tof=status.data?.data.tof; const tofAvailable=tof?.status==="AVAILABLE" || tof?.status==="READY";
  return <><PageHeader eyebrow="Signal workbench" title="Waveform" description="Explore the signal. Select a region to create a gate." actions={<Button onClick={()=>setMode("select")}><Plus/>Add gate</Button>}/>
    <section className="panel !p-0 overflow-hidden"><div className="flex flex-wrap gap-4 items-center border-b px-5 py-4"><div className="flex gap-2 items-center"><Button variant="outline" size="icon" aria-label="Previous frame" disabled={position===0} onClick={()=>changePosition(position-1)}><ChevronLeft/></Button><label className="flex items-center gap-2 text-sm">Frame<Input aria-label="Frame position" className="!w-20" type="number" min={1} max={frames.data.data.frames.length} value={position+1} onChange={e=>changePosition(Math.min(frames.data!.data.frames.length-1,Math.max(0,Number(e.target.value)-1)))}/></label><span className="muted text-xs">of {numberText(frames.data.data.frames.length,0)}</span><Button variant="outline" size="icon" aria-label="Next frame" disabled={position===frames.data.data.frames.length-1} onClick={()=>changePosition(position+1)}><ChevronRight/></Button></div><div className="ml-auto flex gap-4 text-xs muted"><span>Cycle {unique?.cycle_index_raw??"—"}</span><span>Step {unique?.step_index_raw??"—"}</span><span>Reference SOC {numberText(unique?.soc_reference_percent)}%</span></div></div>
      <div className="flex flex-wrap items-center gap-2 px-5 pt-4" role="toolbar" aria-label="Waveform controls">{([{value:"zoom",label:"Zoom",icon:ZoomIn},{value:"pan",label:"Pan",icon:Hand},{value:"select",label:"Select gate",icon:MousePointer2}] as const).map(t=><Button key={t.value} variant={mode===t.value?"secondary":"ghost"} size="sm" aria-pressed={mode===t.value} onClick={()=>setMode(t.value)}><t.icon/>{t.label}</Button>)}<Button variant="ghost" size="sm" onClick={()=>setReset(v=>v+1)}><RotateCcw/>Reset view</Button><span className="ml-auto text-xs muted">Envelope unavailable</span></div>
      <div className="plot-wrap" data-testid="waveform-plot" aria-label="Waveform plot">{preview.error ? <ErrorState error={preview.error} retry={()=>void preview.refetch()}/> : preview.data ? <Suspense fallback={<LoadingState/>}><WaveformPlot preview={preview.data.data} gates={gates.data?.data.gates??[]} draft={draft} mode={mode} reset={reset} onSelect={select}/></Suspense> : <LoadingState/>}</div>
      <div className="px-6 py-3 border-t text-xs muted flex gap-2 items-center"><Badge variant="outline">Sample index</Badge>{mode==="select" ? "Drag horizontally across the signal to propose a gate." : "Scroll to zoom. Double-click to restore the view."} Physical timing is not verified.</div>
    </section>
    {draft && <div className="notice mt-4 items-center"><div className="flex-1"><h3>New gate selection</h3><p className="text-sm">Draft only. Confirm before saving to the experiment.</p></div><Button variant="ghost" onClick={()=>setDraft(null)}>Discard</Button><Button onClick={()=>{setConfirm(true);commit.reset();}}>Review gate</Button></div>}
    {message && <p role="status" className="notice mt-4">{message}</p>}
    <div className="grid md:grid-cols-3 panel !p-0 mt-6"><BlockedValue name="Amplitude" reason="Hover over the waveform for sample amplitude."/><BlockedValue name="TOF" value={tofAvailable ? tof?.value : null} unit="µs" reason={tofAvailable ? "API-provided result" : "Sampling rate required"} action={!tofAvailable && <ParameterDialog/>}/><BlockedValue name="Wave speed" reason="Acoustic path and backend capability required" action={<Button variant="link" size="sm" asChild className="px-0"><Link to={`/experiments/${batteryId}/${experimentId}/advanced/parameters`}>Review parameters</Link></Button>}/></div>
    <div className="mt-6 flex flex-wrap items-center gap-3"><h3>Saved gates</h3>{gates.data?.data.gates.map((g,i)=><Badge variant="secondary" key={g.gate_id}>{g.gate_name??`Gate ${i+1}`}</Badge>)}{gates.data?.data.gates.length===0 && <span className="muted text-sm">Select your first region above.</span>}{gates.error && <span role="status">Saved gates unavailable. Retry the page to reload.</span>}</div>
    <details className="mt-5"><summary>Advanced waveform details & keyboard gate selection</summary><p className="muted text-xs">Frame context is shown only for an unambiguous match in the API event preview. Charge/discharge phase and envelope are not provided by this endpoint.</p><p className="text-xs muted">Peak-to-Peak TOF: unavailable · Absolute arrival: requires verified timing</p><div className="flex gap-3 items-end mt-3"><label className="field">Start sample<Input aria-label="Gate start sample" type="number" min={0} value={draft?.start??0} onChange={e=>setDraft({start:Number(e.target.value),end:draft?.end??1})}/></label><label className="field">End sample<Input aria-label="Gate end sample" type="number" min={1} value={draft?.end??1} onChange={e=>setDraft({start:draft?.start??0,end:Number(e.target.value)})}/></label><Button variant="outline" disabled={!draft || draft.end<=draft.start || draft.start<0 || draft.end>=(preview.data?.data.waveform_length??0)} onClick={()=>setConfirm(true)}>Review gate</Button></div></details><ScopeNote/>
    <Dialog open={confirm} onOpenChange={setConfirm}><DialogContent><DialogHeader><DialogTitle>Save selected gate</DialogTitle><DialogDescription>This will save a signal region for {batteryId} / {experimentId}. It does not calculate new features or change raw waveforms.</DialogDescription></DialogHeader><label className="field">Gate name<Input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. First reflection"/></label><p className="text-sm muted">Selected interval: {draft?.start}–{draft?.end} samples. The backend validates the interval and assigns its identity.</p>{commit.error && <p role="alert">Gate could not be saved. Check the interval and retry.</p>}<DialogFooter><Button variant="outline" onClick={()=>setConfirm(false)}>Cancel</Button><Button disabled={commit.isPending || !draft} onClick={()=>commit.mutate()}>{commit.isPending?"Saving…":"Save gate"}</Button></DialogFooter></DialogContent></Dialog>
  </>;
}
