"""BRW-024R T01-T55: experiment library + intake lifecycle tests.

Sandbox only: tmp raw/processed roots; fixtures are real-format minimal
assets. Real CELL_001/EXP_001 data is never modified.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from battery_workbench.api.app import create_app

REPO = Path(__file__).resolve().parents[2]
FIXTURES = Path("/tmp/brw024r-fixtures")
HAS_FIXTURES = (FIXTURES / "sample_electrical.xlsx").is_file()


@pytest.fixture()
def env(tmp_path: Path) -> tuple[TestClient, Path, Path]:
    raw = tmp_path / "raw"
    processed = tmp_path / "processed"
    # minimal canonical manifests so the orchestrator-facing loaders work
    manifests = raw / "manifests"
    manifests.mkdir(parents=True)
    (manifests / "experiments.csv").write_text(
        "experiment_id,battery_id,start_time,end_time,protocol,notes\n", encoding="utf-8"
    )
    (manifests / "data_assets.csv").write_text(
        "asset_id,experiment_id,modality,relative_path,file_start_time,file_end_time,parser_name,parser_version\n",
        encoding="utf-8",
    )
    (manifests / "batteries.csv").write_text(
        "battery_id,chemistry,nominal_capacity_ah,notes\nCELL_001,,,test\n", encoding="utf-8"
    )
    app = create_app(raw_root=raw, processed_root=processed)
    client = TestClient(app)
    return client, raw, processed


def _create_experiment(
    client: TestClient, exp_id: str = "EXP_001", battery_id: str = "CELL_001"
) -> dict:
    resp = client.post(
        "/api/v1/experiments",
        json={"battery_id": battery_id, "experiment_id": exp_id, "name": "测试实验"},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()["data"]


def _new_session_with_assets(client: TestClient, exp_id: str = "EXP_001") -> str:
    _create_experiment(client, exp_id)
    session = client.post(f"/api/v1/experiments/CELL_001/{exp_id}/intake-sessions").json()["data"]
    for role, fixture in (
        ("ELECTRICAL", "sample_electrical.xlsx"),
        ("ULTRASOUND", "sample_ultrasound.txt"),
    ):
        content = (FIXTURES / fixture).read_bytes()
        up = client.post(
            f"/api/v1/intake-sessions/{session['session_id']}/assets",
            files={"file": (fixture, content, "application/octet-stream")},
            data={"role": role},
        )
        assert up.status_code == 200, up.text
    det = client.post(f"/api/v1/intake-sessions/{session['session_id']}/detect")
    assert det.status_code == 200, det.text
    val = client.post(f"/api/v1/intake-sessions/{session['session_id']}/validate")
    assert val.status_code == 200, val.text
    return session["session_id"]


def _validated_session(client: TestClient, exp_id: str = "EXP_001") -> str:
    sid = _new_session_with_assets(client, exp_id)
    return sid


# ---------- experiment library (T01-T06) ----------
class TestExperimentLibrary:
    def test_t01_create(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        data = _create_experiment(client, "EXP_001")
        assert data["status"] == "AWAITING_DATA"
        assert data["experiment_composite_id"] == "CELL_001/EXP_001"
        assert data["is_demo"] is False

    def test_t02_id_policy_autogenerated(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        data = (
            _create_experiment(client, None)
            if False
            else client.post(
                "/api/v1/experiments",
                json={"battery_id": "CELL_001", "name": "auto"},
            ).json()["data"]
        )
        assert data["experiment_id"] == "EXP_001"
        data2 = client.post(
            "/api/v1/experiments", json={"battery_id": "CELL_001", "name": "auto2"}
        ).json()["data"]
        assert data2["experiment_id"] == "EXP_002"

    def test_t03_duplicate_identity_conflict(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        resp = client.post(
            "/api/v1/experiments",
            json={"battery_id": "CELL_001", "experiment_id": "EXP_001", "name": "dup"},
        )
        assert resp.status_code == 409

    def test_t04_metadata_update(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        resp = client.patch(
            "/api/v1/experiments/CELL_001/EXP_001", json={"name": "改名", "notes": "note"}
        )
        assert resp.status_code == 200
        assert resp.json()["data"]["name"] == "改名"

    def test_t05_demo_flag(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        data = client.post(
            "/api/v1/experiments",
            json={"battery_id": "CELL_001", "name": "demo", "is_demo": True},
        ).json()["data"]
        assert data["is_demo"] is True

    def test_t06_listing_filter_pagination(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        for i in range(1, 4):
            _create_experiment(client, f"EXP_{i:03d}")
        resp = client.get("/api/v1/experiments?limit=2")
        body = resp.json()
        assert len(body["data"]["experiments"]) == 2
        assert body["meta"]["next_cursor"]
        page2 = client.get(
            "/api/v1/experiments", params={"limit": 2, "cursor": body["meta"]["next_cursor"]}
        ).json()
        assert len(page2["data"]["experiments"]) == 1
        filtered = client.get("/api/v1/experiments?status=AWAITING_DATA").json()
        assert len(filtered["data"]["experiments"]) == 3
        demo = client.get("/api/v1/experiments?is_demo=true").json()
        assert demo["data"]["experiments"] == []

    def test_archive(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        resp = client.post("/api/v1/experiments/CELL_001/EXP_001/archive")
        assert resp.status_code == 200
        assert resp.json()["data"]["status"] == "ARCHIVED"


# ---------- intake session (T07-T11) ----------
class TestIntakeSession:
    def test_t07_create(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        resp = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions")
        assert resp.status_code == 200
        assert resp.json()["data"]["session_id"].startswith("INTAKE::")
        assert resp.json()["data"]["status"] == "DRAFT"

    def test_t08_status_transitions(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        session = client.get(f"/api/v1/intake-sessions/{sid}").json()["data"]
        assert session["status"] == "VALIDATED"

    def test_t09_cancel(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        sid = _new_session_with_assets(client) if HAS_FIXTURES else None
        if sid is None:
            pytest.skip("fixtures missing")
        resp = client.post(f"/api/v1/intake-sessions/{sid}/cancel")
        assert resp.status_code == 200
        assert resp.json()["data"]["status"] == "CANCELLED"

    def test_t10_committed_immutable(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        commit = client.post(f"/api/v1/intake-sessions/{sid}/commit")
        assert commit.status_code == 200
        # post-commit mutation rejected
        up = client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("x.txt", b"data", "text/plain")},
            data={"role": "AUXILIARY"},
        )
        assert up.status_code in (409, 400)

    def test_t11_expired_cleanup(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _processed = env
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        engine = client.app.state.workbench_service.intake  # type: ignore[attr-defined]
        removed = engine.cleanup_expired(older_than_iso="9999-12-31")  # future → all expire
        assert sid in removed
        removed2 = engine.cleanup_expired(older_than_iso="9999-12-31")
        assert removed2 == []  # already expired → no double removal
        session = client.get(f"/api/v1/intake-sessions/{sid}").json()["data"]
        assert session["status"] == "EXPIRED"


# ---------- upload (T12-T17) ----------
class TestUpload:
    def test_t12_unsafe_filename_rejected(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        resp = client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("../../etc/passwd", b"x", "text/plain")},
            data={"role": "AUXILIARY"},
        )
        assert resp.status_code == 400

    def test_t13_sha256_recorded(self, env: tuple[TestClient, Path, Path]) -> None:
        import hashlib

        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        content = (FIXTURES / "sample_ultrasound.txt").read_bytes()
        resp = client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("sample_ultrasound.txt", content, "text/plain")},
            data={"role": "ULTRASOUND"},
        )
        assert resp.status_code == 200
        assert resp.json()["data"]["sha256"] == hashlib.sha256(content).hexdigest()

    def test_t14_oversize_rejected(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        resp = client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("big.bin", b"x" * (101 * 1024 * 1024), "application/octet-stream")},
            data={"role": "AUXILIARY"},
        )
        assert resp.status_code == 413

    def test_t15_multiple_assets(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        assets = client.get(f"/api/v1/intake-sessions/{sid}/assets").json()["data"]["assets"]
        assert len(assets) == 2

    def test_t16_same_checksum_upload_twice(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        # same bytes, same role → policy: allowed as separate staged asset records
        # (commit deduplicates against canonical raw by checksum)
        content = (FIXTURES / "sample_ultrasound.txt").read_bytes()
        resp = client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("again.txt", content, "text/plain")},
            data={"role": "ULTRASOUND"},
        )
        assert resp.status_code == 200

    def test_t17_same_name_different_checksum(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        resp = client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("sample_ultrasound.txt", b"corrupted", "text/plain")},
            data={"role": "ULTRASOUND"},
        )
        assert resp.status_code == 200  # staged as a distinct record; conflict surfaces at commit
        assets = client.get(f"/api/v1/intake-sessions/{sid}/assets").json()["data"]["assets"]
        assert len(assets) == 3


# ---------- adapter detection (T18-T23) ----------
class TestDetection:
    def test_t18_electrical_detected(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        resp = client.post(f"/api/v1/intake-sessions/{sid}/detect")
        assert resp.status_code == 200
        detections = resp.json()["data"]["detections"]
        electrical = next(d for d in detections if d["asset_role"] == "ELECTRICAL")
        assert electrical["state"] == "DETECTED_UNIQUE"
        assert electrical["adapter_id"] == "ElectricalAdapter"
        assert electrical["modality"] == "electrical"

    def test_t19_ultrasound_detected(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        detections = client.post(f"/api/v1/intake-sessions/{sid}/detect").json()["data"][
            "detections"
        ]
        ultrasound = next(d for d in detections if d["asset_role"] == "ULTRASOUND")
        assert ultrasound["state"] == "DETECTED_UNIQUE"
        assert ultrasound["adapter_id"] == "UltrasoundAdapter"

    def test_t20_unsupported_stops(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("mystery.parquet", b"PAR1 fake", "application/octet-stream")},
            data={"role": "AUXILIARY"},
        )
        resp = client.post(f"/api/v1/intake-sessions/{sid}/detect")
        assert resp.status_code == 409
        assert resp.json()["error"]["code"] == "UNSUPPORTED_FILE_FORMAT"

    def test_t21_ambiguous_stops(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        # ".txt" is ultrasound; craft ambiguous via two matches is registry-dependent —
        # force ambiguity by monkeypatching registry modalities
        engine = client.app.state.workbench_service.intake  # type: ignore[attr-defined]
        session = engine.load_session(sid)
        asset = engine.store_asset(
            session,
            role="ULTRASOUND",
            original_filename="both.txt",
            content=b"data",
        )
        import battery_workbench.intake.engine as engine_mod
        from battery_workbench.intake.engine import (
            ULTRASOUND_SUFFIXES,
        )

        original = set(ULTRASOUND_SUFFIXES)
        engine_mod.ULTRASOUND_SUFFIXES = {".txt", ".xlsx"}  # type: ignore[misc]
        try:
            (engine.staging_dir(sid) / asset.stored_filename).rename(
                engine.staging_dir(sid) / (asset.intake_asset_id + ".xlsx")
            )
            asset.stored_filename = asset.intake_asset_id + ".xlsx"
            engine.save_session(session)
            resp = client.post(f"/api/v1/intake-sessions/{sid}/detect")
            assert resp.status_code == 409
            assert resp.json()["error"]["code"] == "AMBIGUOUS_ADAPTER"
        finally:
            engine_mod.ULTRASOUND_SUFFIXES = original  # type: ignore[misc]

    def test_t22_content_over_extension(self, env: tuple[TestClient, Path, Path]) -> None:
        """extension/MIME is a hint; registry decides. A .txt with xlsx bytes is unsupported, not xlsx."""
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("fake.txt", b"PK\x03\x04 not really xlsx", "text/plain")},
            data={"role": "ULTRASOUND"},
        )
        resp = client.post(f"/api/v1/intake-sessions/{sid}/detect")
        # detected by suffix as ultrasound, but validation must fail (content not frames)
        assert resp.status_code == 200
        validate = client.post(f"/api/v1/intake-sessions/{sid}/validate")
        assert validate.json()["data"]["overall_passed"] is False

    def test_t23_detection_provenance(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        detections = client.post(f"/api/v1/intake-sessions/{sid}/detect").json()["data"][
            "detections"
        ]
        for d in detections:
            assert d["adapter_version"]
            assert d["detection_reason"]
            assert d["matched_signatures"]


# ---------- validation (T24-T29) ----------
class TestValidation:
    def test_t24_electrical_structure(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        validation = client.post(f"/api/v1/intake-sessions/{sid}/validate").json()["data"]
        assert validation["overall_passed"] is True

    def test_t25_ultrasound_structure(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        validation = client.post(f"/api/v1/intake-sessions/{sid}/validate").json()["data"]
        ultrasound_check = next(
            c for c in validation["checks"] if "ultrasound frames" in c["detail"]
        )
        assert ultrasound_check["passed"] is True
        assert "frames=5" in ultrasound_check["detail"]
        assert "1250" in ultrasound_check["detail"]

    def test_t26_unknown_fs_stays_null(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        validation = client.post(f"/api/v1/intake-sessions/{sid}/validate").json()["data"]
        assert validation["sampling_rate_hz"] is None
        assert validation["sampling_rate_status"] == "UNKNOWN"

    def test_t27_cadence_never_fs(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        validation = client.post(f"/api/v1/intake-sessions/{sid}/validate").json()["data"]
        detail = " ".join(c["detail"] for c in validation["checks"])
        assert "10s frame cadence is NOT a waveform fs" in detail
        # fixture cadence ≈10.031s → 1/10.031 ≈ 0.0997 Hz must not appear as fs
        assert validation["sampling_rate_hz"] is None

    def test_t28_missing_required_role(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        content = (FIXTURES / "sample_electrical.xlsx").read_bytes()
        client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("sample_electrical.xlsx", content, "application/octet-stream")},
            data={"role": "ELECTRICAL"},
        )
        client.post(f"/api/v1/intake-sessions/{sid}/detect")
        validation = client.post(f"/api/v1/intake-sessions/{sid}/validate").json()["data"]
        readiness = next(c for c in validation["checks"] if c["dimension"] == "PIPELINE_READINESS")
        assert readiness["passed"] is False
        assert validation["overall_passed"] is False

    def test_t29_metadata_incomplete_not_format_invalid(
        self, env: tuple[TestClient, Path, Path]
    ) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _new_session_with_assets(client)
        validation = client.post(f"/api/v1/intake-sessions/{sid}/validate").json()["data"]
        by_dim = {c["dimension"]: c for c in validation["checks"]}
        # format valid
        assert by_dim["FORMAT_VALIDITY"]["passed"] is True
        # fs unknown is metadata, NOT a format failure
        assert validation["sampling_rate_status"] == "UNKNOWN"
        assert validation["overall_passed"] is True  # intake valid despite unknown fs


# ---------- commit (T30-T36) ----------
class TestCommit:
    def test_t30_commit_validated(self, env: tuple[TestClient, Path, Path]) -> None:
        client, raw, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        commit = client.post(f"/api/v1/intake-sessions/{sid}/commit")
        assert commit.status_code == 200
        data = commit.json()["data"]
        assert data["experiment_composite_id"] == "CELL_001/EXP_001"
        assert len(data["assets"]) == 2
        # canonical raw now contains the files
        assert (raw / "batteries/CELL_001/EXP_001/electrical/sample_electrical.xlsx").is_file()
        assert (raw / "batteries/CELL_001/EXP_001/ultrasound/sample_ultrasound.txt").is_file()
        # experiment lifecycle advanced
        exp = client.get("/api/v1/experiments/CELL_001/EXP_001").json()["data"]
        assert exp["status"] == "READY_FOR_PIPELINE"
        assert exp["asset_summary"]["committed_assets"] == 2

    def test_t31_repeat_commit_idempotent(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        first = client.post(f"/api/v1/intake-sessions/{sid}/commit").json()["data"]
        second = client.post(f"/api/v1/intake-sessions/{sid}/commit")
        assert second.status_code == 200
        assert (
            second.json()["data"]["import_manifest_checksum"] == first["import_manifest_checksum"]
        )

    def test_t32_unvalidated_blocked(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        _create_experiment(client, "EXP_001")
        sid = client.post("/api/v1/experiments/CELL_001/EXP_001/intake-sessions").json()["data"][
            "session_id"
        ]
        content = (FIXTURES / "sample_ultrasound.txt").read_bytes()
        client.post(
            f"/api/v1/intake-sessions/{sid}/assets",
            files={"file": ("sample_ultrasound.txt", content, "text/plain")},
            data={"role": "ULTRASOUND"},
        )
        resp = client.post(f"/api/v1/intake-sessions/{sid}/commit")
        assert resp.status_code == 409
        assert resp.json()["error"]["code"] == "INTAKE_NOT_VALIDATED"

    def test_t33_rollback_on_conflict(self, env: tuple[TestClient, Path, Path]) -> None:
        client, raw, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        # pre-place a conflicting file at the canonical destination
        conflict = raw / "batteries/CELL_001/EXP_001/electrical"
        conflict.mkdir(parents=True, exist_ok=True)
        (conflict / "sample_electrical.xlsx").write_bytes(b"CONFLICTING CONTENT")
        resp = client.post(f"/api/v1/intake-sessions/{sid}/commit")
        assert resp.status_code == 409
        assert resp.json()["error"]["code"] == "INTEGRITY_ERROR"
        # conflicting file untouched; no partial manifest rows
        assert (conflict / "sample_electrical.xlsx").read_bytes() == b"CONFLICTING CONTENT"
        assets_csv = (raw / "manifests/data_assets.csv").read_text(encoding="utf-8")
        assert "EXP_001" not in assets_csv

    def test_t34_asset_registry(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        client.post(f"/api/v1/intake-sessions/{sid}/commit")
        assets = client.get("/api/v1/experiments/CELL_001/EXP_001/assets").json()["data"]["assets"]
        assert len(assets) == 2
        for a in assets:
            assert a["asset_id"]
            assert a["modality"] in ("electrical", "ultrasound")

    def test_t35_manifest_provenance(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        result = client.post(f"/api/v1/intake-sessions/{sid}/commit").json()["data"]
        for a in result["assets"]:
            assert a["parser_name"] in ("ElectricalAdapter", "UltrasoundAdapter")
            assert a["intake_session_id"] == sid
            assert a["sha256"]
        assert result["import_manifest_checksum"]

    def test_t36_raw_immutable_after_commit(self, env: tuple[TestClient, Path, Path]) -> None:
        client, raw, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        sid = _validated_session(client)
        client.post(f"/api/v1/intake-sessions/{sid}/commit")
        committed = (
            raw / "batteries/CELL_001/EXP_001/ultrasound/sample_ultrasound.txt"
        ).read_bytes()
        # re-commit same content via a new session → same bytes reused (no overwrite with different bytes)
        _create_experiment(client, "EXP_002")
        sid2 = client.post("/api/v1/experiments/CELL_001/EXP_002/intake-sessions").json()["data"][
            "session_id"
        ]
        content = (FIXTURES / "sample_ultrasound.txt").read_bytes()
        client.post(
            f"/api/v1/intake-sessions/{sid2}/assets",
            files={"file": ("sample_ultrasound.txt", content, "text/plain")},
            data={"role": "ULTRASOUND"},
        )
        client.post(f"/api/v1/intake-sessions/{sid2}/detect")
        client.post(f"/api/v1/intake-sessions/{sid2}/validate")
        resp = client.post(f"/api/v1/intake-sessions/{sid2}/commit")
        # either 200 with identical bytes reused, or 409 integrity error on checksum conflict
        if resp.status_code == 200:
            now_bytes = (
                raw / "batteries/CELL_001/EXP_001/ultrasound/sample_ultrasound.txt"
            ).read_bytes()
            assert now_bytes == committed
        else:
            assert resp.status_code == 409


# ---------- security / error mapping (T46-T50) ----------
class TestSecurityAndErrors:
    def test_t37_capabilities(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        resp = client.get("/api/v1/intake/capabilities")
        assert resp.status_code == 200
        caps = resp.json()["data"]
        assert any(a["adapter_id"] == "ElectricalAdapter" for a in caps["adapters"])
        assert any(a["adapter_id"] == "UltrasoundAdapter" for a in caps["adapters"])
        assert "ELECTRICAL" in caps["supported_roles"]

    def test_t38_create_and_list(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        assert client.get("/api/v1/experiments").status_code == 200

    def test_t47_traversal_in_ids(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        resp = client.get("/api/v1/intake-sessions/..%2F..%2Fetc")
        assert resp.status_code in (400, 404)
        resp = client.get("/api/v1/intake-sessions/INTAKE::abc%2F..%2Fpasswd")
        assert resp.status_code in (400, 404)

    def test_t48_no_arbitrary_path(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        # create-experiment payload cannot inject path
        resp = client.post(
            "/api/v1/experiments",
            json={"battery_id": "../evil", "name": "x"},
        )
        assert resp.status_code == 400

    def test_t50_no_path_leak(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        _create_experiment(client, "EXP_001")
        resp = client.get("/api/v1/intake-sessions/INTAKE::nonexistent")
        body = resp.json()
        serialized = str(body)
        assert "/private/var" not in serialized and "/tmp/" not in serialized


# ---------- isolation (T51-T55) ----------
class TestIsolation:
    def test_t54_multi_experiment_isolated(self, env: tuple[TestClient, Path, Path]) -> None:
        client, raw, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        for exp in ("EXP_001", "EXP_002"):
            sid = _validated_session(client, exp)
            assert client.post(f"/api/v1/intake-sessions/{sid}/commit").status_code == 200
        e1 = raw / "batteries/CELL_001/EXP_001/ultrasound/sample_ultrasound.txt"
        e2 = raw / "batteries/CELL_001/EXP_002/ultrasound/sample_ultrasound.txt"
        assert e1.is_file() and e2.is_file()
        # same filename, isolated directories
        assert (
            raw / "batteries/CELL_001/EXP_001/ultrasound/sample_ultrasound.txt"
        ).parent.name == "ultrasound"
        assets1 = client.get("/api/v1/experiments/CELL_001/EXP_001/assets").json()["data"]["assets"]
        assets2 = client.get("/api/v1/experiments/CELL_001/EXP_002/assets").json()["data"]["assets"]
        assert {a["asset_id"] for a in assets1}.isdisjoint({a["asset_id"] for a in assets2})

    def test_t55_overlapping_locators_isolated(self, env: tuple[TestClient, Path, Path]) -> None:
        client, _, _ = env
        if not HAS_FIXTURES:
            pytest.skip("fixtures missing")
        for exp in ("EXP_001", "EXP_002"):
            sid = _validated_session(client, exp)
            client.post(f"/api/v1/intake-sessions/{sid}/commit")
        h1 = client.get("/api/v1/experiments/CELL_001/EXP_001/intake-history").json()["data"][
            "history"
        ]
        h2 = client.get("/api/v1/experiments/CELL_001/EXP_002/intake-history").json()["data"][
            "history"
        ]
        assert len(h1) == 1 and len(h2) == 1
        assert h1[0]["session_id"] != h2[0]["session_id"]
